GET {{URL}}/api/users/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

##########################################

GET {{URL}}/api/users/own/profile
Content-Type: application/json
Authorization: Bearer {{auth_token}}

##########################################

GET {{URL}}/api/users/{{otherUserId}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

##########################################

PUT {{URL}}/api/users/{{otherUserId}}/invite
Content-Type: application/json
Authorization: Bearer {{auth_token}}
##########################################

PUT {{URL}}/api/users/{{userId}}/approve
Content-Type: application/json
Authorization: Bearer {{other_auth_token}}

##########################################

GET {{URL}}/api/users/{{otherUserId}}/posts
Content-Type: application/json
Authorization: Bearer {{auth_token}}

##########################################

GET {{URL}}/api/users/{{otherUserId}}/comments
Content-Type: application/json
Authorization: Bearer {{auth_token}}