POST {{URL}}/api/auth/register
Content-Type: application/json

{
  "login": "login_1",
  "password": "some_password"
}

#################################################
POST {{URL}}/api/auth/register
Content-Type: application/json

{
  "login": "login_2",
  "password": "some_password"
}

#################################################
POST {{URL}}/api/auth/login
Content-Type: application/json

{
  "login": "login_1",
  "password": "some_password"
}

#################################################
POST {{URL}}/api/auth/login
Content-Type: application/json

{
  "login": "login_1",
  "password": "another_password"
}

#################################################
POST {{URL}}/api/auth/login
Content-Type: application/json

{
  "login": "login_2",
  "password": "some_password"
}