POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "login": "login_1",
  "password": "some_password"
}

##########################################
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "login": "login_1",
  "password": "some_password"
}

##########################################

POST http://localhost:3000/api/comment/write
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "content": "some_comment_1",
  "postId": "628b6f038b43f97cdd8ff163"
}

##########################################

GET http://localhost:3000/api/comment/own
Content-Type: application/json
Authorization: Bearer {{auth_token}}

##########################################

GET http://localhost:3000/api/comment/post/{{post_id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

##########################################

GET http://localhost:3000/api/comment/author/{{user_id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}