POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "login": "login_1",
  "password": "some_password"
}

##########################################
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "login": "login_1",
  "password": "some_password"
}

##########################################

POST http://localhost:3000/api/post/write
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mjg5ZmUyNDA1OWFlNzBiMzNkODZmZTMiLCJpYXQiOjE2NTMzMDQ4NjAsImV4cCI6MTY1MzMxNTY2MH0.knhIc5buBK2MiiIOq4BoMO4kftITYz_JDbK9iji_C1E

{
  "content": "some_content_6"
}

##########################################

GET http://localhost:3000/api/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mjg5ZmUyNDA1OWFlNzBiMzNkODZmZTMiLCJpYXQiOjE2NTM0MzQzMjksImV4cCI6MTY1MzQ0NTEyOX0.LGSciBkcP58AlzPAGD3T_xiXqnPTWxDq9Gdgv78aU4M

##########################################

GET http://localhost:3000/api/user/6289fe8c059ae70b33d86fe7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mjg5ZmUyNDA1OWFlNzBiMzNkODZmZTMiLCJpYXQiOjE2NTM0MzQzMjksImV4cCI6MTY1MzQ0NTEyOX0.LGSciBkcP58AlzPAGD3T_xiXqnPTWxDq9Gdgv78aU4M

##########################################

GET http://localhost:3000/api/post/author/{{user_id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}