POST {{URL}}/api/posts
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "content": "some_post_content_7"
}

##########################################

GET {{URL}}/api/posts/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

##########################################

GET {{URL}}/api/posts/{{postId}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

##########################################

GET {{URL}}/api/posts/{{postId}}/comments
Content-Type: application/json
Authorization: Bearer {{auth_token}}

##########################################

POST {{URL}}/api/posts/{{postId}}/comments
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "content": "some_post_comment_7"
}