GET {{URL}}/api/comments
Content-Type: application/json
Authorization: Bearer {{auth_token}}

##########################################

GET {{URL}}/api/comments/{{commentId}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

##########################################
PUT {{URL}}/api/comments/{{commentId}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "content": "changed_content_1"
}

##########################################

DELETE {{URL}}/api/comments/{{commentId}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

##########################################
